### ISSUE TITLE
Plain strings for cy.mount

### ISSUE THREAD

**Issue by PaulHax** [redfox-mx/cypress-lit#40]
Would be nice if we could pass normal strings to the `cy.mount` call sometimes instead of requiring `lit` `html` templates. 

`cy.mount('<div id="container"></div>')` <- pretty please?

Thanks for the lib, fixes mount lifecycle problem I have with https://github.com/simonireilly/cypress-lit

Somehow that lib supports passing plain strings to `cy.mount`

**Comment by redfox-mx** [comment]
Hi @PaulHax it souds interesting, maybe is not so difficult to implement. BTW what are the reason behind prefer strings over lit syntax?

**Comment by PaulHax** [comment]
Keeps the same typing as the original `cy.mount` and would have made my transition from `cypress-lit` completly transparent.  Most of my monorepo packages don't depend on `lit` but I still want to mount in their tests: https://github.com/InsightSoftwareConsortium/itk-viewer

**Comment by redfox-mx** [comment]
fixed in #47 an released with [cypress-ct-lit@0.5.0](https://www.npmjs.com/package/cypress-ct-lit)
